Strint 1/step 2
filaretovdmitriy/reactburger pull request #1
Opened 2023-03-15 15:45 UTC by filaretovdmitriy

Сдача на проверку

2023-03-15 16:15 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете `useEffect` и `PropTypes`.

Что понравилось:
- Есть отписка от слушателя событий
- Хорошая декомпозиция компонентов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У верхней и нижней булки должны быть надписи "Верх" и "Низ" соответственно.
- Добавьте проверку успешности запроса
- Добавьте `isRequired` там где его не хватает.
- Уберите дубликаты `propTypes` ингредиента
- Для модалки нужно в файле index.html создать div с id - modals и в него следует внедрять модалку через createPortal.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-15 16:15 UTC, andryxxa93 commented on src/components/burgerconstructor/burgerconstructor.jsx
> +  type: PropTypes.string,
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2023-03-16 07:34 UTC, filaretovdmitriy commented on src/components/modal/modal.jsx
> +  const node = document.createElement("div");
Исправлено

2023-03-16 09:10 UTC, filaretovdmitriy reviewed
Обновлено

2023-03-16 09:10 UTC, filaretovdmitriy commented on src/App.jsx
> +    const getIngredients = async () => {
Доработано

2023-03-16 09:11 UTC, merged